language: node_js
node_js:
- '10'
script: npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  edge: true
  token:
    secure: "S6MLtqX7ctr0xGMqtuwYIhpbetUCaqr7BdWGKyE68JFx5+8aEu4lo/5BrUyld8XJXau5YFrFQnt7f70HoYD1+RROHknvnhhdUyVdAtFkmK2NsyuGo8sKBJ5b44Foniui4BKOpyx7Y0TF52MVT+juzbra/BzRJiomE7Aw7od5Jzus02R68FvnXtvxrMLGhuKbopWHW9jysEeAklzM2TLjbvjd3UvJpEZdSrz/jyLydJ6SL/eZej7+6AsI+JkueusIDKMWqaLYemiVyzly5fv0TeGgG6vTkkjbmfTTOuZ9KeAcBZA4zKnIBpgkYB5Fo0IQN7uoKQpyAZF5faj3bnwj7ztk9ORZJhUAIpyOi5K2iupKUM1i0fYaXm7HaoRxAeXva1gt0jr1WxHdYdorkn2EVIoQcUiXHvw3VRgvmbmlGsPtYwAnwknmjP+YdHv/PXVIT96Rsv7MOImIjBjTQJ7AQCI6A+gNTf5S4QKzJ/qWmgYmchZqRIFQyM3gY5Bl1JrIF60SEh+vw1LmmhpUAcwagxNJvsQZEOhVraQ3bGsIbPC5g8R/0yxmBxRYw03kM1ctfrhQpc5h33NndCqHSl9B26FjFpQLGbnZ2NikEi24yaf/xPsvpQKsygS+54A/I/UEKfRnbOWnJmJ0kKi61GeMcdGqEdoFBLhghb5FnoVZelk="
